In [25]:
import numpy as np

In [2]:
# array operations
a = np.array([10,10,10,10])
b = np.array([5,5,5,5])

In [3]:
a+b

array([15, 15, 15, 15])

In [4]:
a - b

array([5, 5, 5, 5])

In [5]:
a*b

array([50, 50, 50, 50])

In [6]:
a/b

array([2., 2., 2., 2.])

In [7]:
a%3

array([1, 1, 1, 1], dtype=int32)

In [8]:
a < 35


array([ True,  True,  True,  True])

In [9]:
a>25

array([False, False, False, False])

In [11]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
print('A:\n',A)
print('B:\n',B)

A:
 [[1 1]
 [0 1]]
B:
 [[2 0]
 [3 4]]


In [12]:
A+B

array([[3, 1],
       [3, 5]])

In [13]:
# Matrix Multiplication
A.dot(B)

array([[5, 4],
       [3, 4]])

In [14]:
# Anotheer method for matrix multiplication
np.dot(A,B)

array([[5, 4],
       [3, 4]])

In [19]:
a *= 3
a

array([90, 90, 90, 90])

In [18]:
b += a
b

array([65, 65, 65, 65])

In [20]:
# we can sum all elements in array
# we can findout min and max values
ages = np.array([1,2,3,4,5,6])

In [21]:
ages.sum()

21

In [22]:
ages.min()

1

In [23]:
ages.max()

6

In [28]:
numbers = np.arange(12).reshape(3,4)
numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
# sum of all column values
numbers.sum(axis=0)

array([12, 15, 18, 21])

In [30]:
#for summing all rows values to  use axis = 1
numbers.sum(axis=1)

array([ 6, 22, 38])

In [31]:
# finding minimum element in a row
numbers.min(axis=1)

array([0, 4, 8])

In [32]:
# finding minimum element in a column
numbers.min(axis=0)

array([0, 1, 2, 3])

In [33]:
numbers.max(axis=0)

array([ 8,  9, 10, 11])

In [35]:
numbers.max(axis=1)

array([ 3,  7, 11])