In [1]:
import numpy as np

In [2]:
a = np.arange(11)**2

In [3]:
a


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [4]:
a[2]

4

In [5]:
a[-2]

81

In [6]:
a[2:7]

array([ 4,  9, 16, 25, 36], dtype=int32)

In [7]:
a[2:-2]

array([ 4,  9, 16, 25, 36, 49, 64], dtype=int32)

In [8]:
a[:2]

array([0, 1], dtype=int32)

In [9]:
a[2:]

array([  4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [10]:
a[:7]

array([ 0,  1,  4,  9, 16, 25, 36], dtype=int32)

In [11]:
# Step through an elemrnts
# Starting to 11 elemnts but stepping 2
a[:12:2]

array([  0,   4,  16,  36,  64, 100], dtype=int32)

In [15]:
# Step to reverse stepping
# Reverse direction
# Stepping the -1 - means backward
a[::-1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0], dtype=int32)

In [16]:
# skipping the one element backward
a[::-2]

array([100,  64,  36,  16,   4,   0], dtype=int32)

In [18]:
# There is no need to all elemrnts in same data type
students = np.array([['Alice','Beth','cathy','Dorothy'],['65','78','90','81'],['71','82','79','92']])

In [21]:
# symbol '<' - Little endian
# symbol '>' Big endian
# symblo 'U' Unicode
students

array([['Alice', 'Beth', 'cathy', 'Dorothy'],
       ['65', '78', '90', '81'],
       ['71', '82', '79', '92']], dtype='<U7')

In [23]:
# First Row of the array
students[0]

array(['Alice', 'Beth', 'cathy', 'Dorothy'], dtype='<U7')

In [24]:
# second Row of the array
students[1]

array(['65', '78', '90', '81'], dtype='<U7')

In [25]:
# Last elements in the array
students[-1]

array(['71', '82', '79', '92'], dtype='<U7')

In [26]:
students[0,1]

'Beth'

In [29]:
students[0:2,2:4]

array([['cathy', 'Dorothy'],
       ['90', '81']], dtype='<U7')

In [30]:
students[:,1:2]

array([['Beth'],
       ['78'],
       ['82']], dtype='<U7')

In [36]:
students[:,0:1]

array([['Alice'],
       ['65'],
       ['71']], dtype='<U7')

In [37]:
students[:1,0:1]

array([['Alice']], dtype='<U7')

In [40]:
students[-1,:-2]

array(['71', '82'], dtype='<U7')

In [41]:
students[0,...]

array(['Alice', 'Beth', 'cathy', 'Dorothy'], dtype='<U7')

In [43]:
students[1,]

array(['65', '78', '90', '81'], dtype='<U7')

In [44]:
students[0,]

array(['Alice', 'Beth', 'cathy', 'Dorothy'], dtype='<U7')

In [45]:
students[...,1]

array(['Beth', '78', '82'], dtype='<U7')