In [1]:
import numpy as np

In [2]:
a = np.arange(11)**2

In [3]:
a


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [7]:
for i in a:
    print(i**(1/2))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [10]:
students = np.array([['Alice','Beth','cathy','Dorothy'],['65','78','90','81'],['71','82','79','92']])

In [11]:
for i in students:
    print('i==',i)

i== ['Alice' 'Beth' 'cathy' 'Dorothy']
i== ['65' '78' '90' '81']
i== ['71' '82' '79' '92']


In [13]:
# Printing all row elements in sequentially
# flatten is in-built function in numpy
for elements in students.flatten():
    print(elements)

Alice
Beth
cathy
Dorothy
65
78
90
81
71
82
79
92


In [14]:
# Printing all column wise elements in sequentially
# flatten is in-built function in numpy
for elements in students.flatten(order='F'):
    print(elements)

Alice
65
71
Beth
78
82
cathy
90
79
Dorothy
81
92


In [16]:
z = np.arange(12).reshape(3,4)
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
# It prints the row format
for i in np.nditer(z):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [18]:
# flattern - Actually returns a result array
# nditer - Just allows you to iterate over elements
for i in np.nditer(z,order='F'):
    print(i)


0
4
8
1
5
9
2
6
10
3
7
11


In [19]:
# For Iterating column-wise-each column is a 1-D array
for i in np.nditer(z,order='F',flags = ['external_loop']):
    print(i)


[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [20]:
# elements iteration itself
# multiplying the value itself
# elipses (...) are used to iterate current elements of the array 
for arr in np.nditer(z,op_flags = ['readwrite']):
    arr[...] = arr*arr
z


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [22]:
z


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])