In [1]:
import numpy as np

In [2]:
angles = np.array([0,30,45,60,90])

In [4]:
# Converting angles to radians
# pi value available numpy package also
angles_radians = angles * np.pi/180
angles_radians

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [5]:
print('sine of angles in the array:')
print(np.sin(angles_radians))

sine of angles in the array:
[0.         0.5        0.70710678 0.8660254  1.        ]


In [6]:
angles_radians = np.radians(angles)
angles_radians

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [19]:
print('Cosine of angles in the arry:')
print(np.cos(angles_radians))

Cosine of angles in the arry:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [9]:
print('Tangent of angles in the arry:')
print(np.tan(angles_radians))

Tangent of angles in the arry:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [11]:
sin = np.sin(angles * np.pi/180)
print('Compute sine inverse of angles. Returned values in radians')
inv = np.arcsin(sin)
print(inv)

Compute sine inverse of angles. Returned values in radians
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


In [12]:
# Converting the to degree
print('Check result by converting to degrees')
print(np.degrees(inv))

Check result by converting to degrees
[ 0. 30. 45. 60. 90.]


In [16]:
test_scores = np.array([32.32,56.98,21.52,44.32,55.63,13.75,43.47,43.34])

In [17]:
print('Mean (avg) of the test scores')
print(np.mean(test_scores))

Mean (avg) of the test scores
38.91625


In [18]:
print('Median test scores  of the students ')
print(np.median(test_scores))

Median test scores  of the students 
43.405


In [20]:
print('variant of the student data')
print(np.var(test_scores))

variant of the student data
206.8294234375


In [28]:
salaries = np.genfromtxt('C:\\home\\uploads\\JISPTbatch\\DATAQ\\OBA_KO-QSI-FCTR_Copy\\LOG\\salary.csv',delimiter=',')

In [38]:
salaries = salaries.reshape(74,24)


In [39]:
salaries.shape

(74, 24)

In [41]:
# Removing elipses
np.set_printoptions(threshold = np.nan)

array([[          nan,           nan, 1.3000000e+01, 7.0000000e+02,
                  nan,           nan,           nan,           nan,
        1.2000000e+01, 1.2000000e+01, 1.1414000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 7.0000000e+00,
        7.0000000e+00, 6.0000000e+00, 1.1530406e+03, 0.0000000e+00],
       [          nan,           nan, 1.3000000e+01, 7.0000000e+02,
                  nan,           nan,           nan,           nan,
        1.2000000e+01, 1.2000000e+01, 1.3164000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 7.0000000e+00,
        7.0000000e+00, 6.0000000e+00, 1.3135239e+03, 0.0000000e+00],
       [          nan,           nan, 1.3000000e+01, 7.0000000e+02,
                  nan,           nan,           nan,           nan,
        0.0000000e+00, 1.2000000e+01, 6.920000

In [43]:
mean     = np.mean(test_scores)
median   = np.median(test_scores)
sd       = np.std(test_scores)
variance = np.var(test_scores) 

In [44]:
print('Mean = %i' %mean)
print('Median = %i'%median)
print()
print('Variance = %i'%variance)

Mean = 38
Median = 43
Variance = 206
